version: 2.1

commands:
  create_concatenated_package_lock:
    description: "Concatenate all package-lock.json files recognized by lerna.js into single file. File is used as checksum source for part of caching key."
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Combine package-lock.json files to single file
          command: npx lerna la -a | awk -F packages '{printf "\"packages%s/package-lock.json\" ", $2}' | xargs cat > << parameters.filename >>

executors:
  node-executor:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm i
      - run: npm run lerna -- bootstrap
      - run: npm run lerna -- run build
      - persist_to_workspace:
          root: .
          paths: ./dist/website

  test-cdk:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm i
      - run: npm run lerna -- bootstrap
      - run: npm run lerna -- --scope cdk run test

  test-website:
    docker:
      - image: trion/ng-cli-karma
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: npm i
      - run: npm run lerna -- bootstrap
      - run: npm run lerna -- --scope website run test:ci
      - store_test_results:
          path: ./packages/website/test-results

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm i
      - run: npm run lerna -- bootstrap
      - run: npm run lerna -- run deploy:ci

workflows:
  build-test-deploy:
    jobs:
      - build:
          context: Website
      - test-website:
          context: Website
      - test-cdk:
          context: Website
          requires:
            - build
      - manual-approval:
          type: approval # presents manual approval button in the UI
          requires:
            - build
            - test-cdk
            - test-website
      - deploy:
          context: Website
          requires:
            - manual-approval
